// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/metrics/ping": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "ping",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/movies/{id}": {
            "get": {
                "description": "Responds with the movie",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movie"
                ],
                "summary": "Get movie by its id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "movie id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MovieDTO"
                        }
                    }
                }
            }
        },
        "/recommendations/movies": {
            "post": {
                "description": "Responds with the list of movies, which is the best recommendations for given user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recommendations"
                ],
                "summary": "Get movies recommendations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "query limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MoviePreview"
                            }
                        }
                    }
                }
            }
        },
        "/search/movies": {
            "get": {
                "description": "Responds with the list of all books, which satisfies query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search movies by query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query to search",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MoviePreview"
                            }
                        }
                    }
                }
            }
        },
        "/search/movies/autocomplete": {
            "get": {
                "description": "Responds with the list of all movies, which title satisfies query",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Autocomplete movies title",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query to search",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MoviePreview"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CastDTO": {
            "type": "object",
            "properties": {
                "character": {
                    "type": "string",
                    "example": "Captain Jack Sparrow"
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "name": {
                    "type": "string",
                    "example": "Johnny Depp"
                }
            }
        },
        "models.Company": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "name": {
                    "type": "string",
                    "example": "Warner Brothers"
                }
            }
        },
        "models.Country": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "UK"
                },
                "name": {
                    "type": "string",
                    "example": "United Kingdom"
                }
            }
        },
        "models.CrewDTO": {
            "type": "object",
            "properties": {
                "department": {
                    "type": "string",
                    "example": "Videography"
                },
                "gender": {
                    "type": "string",
                    "example": "Male"
                },
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "job": {
                    "type": "string",
                    "example": "Camera man"
                },
                "name": {
                    "type": "string",
                    "example": "Johnny Depp"
                }
            }
        },
        "models.Genre": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "name": {
                    "type": "string",
                    "example": "horror"
                }
            }
        },
        "models.Keyword": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "name": {
                    "type": "string",
                    "example": "science"
                }
            }
        },
        "models.Language": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "EN"
                },
                "name": {
                    "type": "string",
                    "example": "English"
                }
            }
        },
        "models.MovieDTO": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "integer",
                    "example": 10000
                },
                "cast": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CastDTO"
                    }
                },
                "countries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Country"
                    }
                },
                "crew": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CrewDTO"
                    }
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Genre"
                    }
                },
                "homepage": {
                    "type": "string",
                    "example": "http://www.sinistermovie.com/"
                },
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Keyword"
                    }
                },
                "languages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Language"
                    }
                },
                "originalLanguage": {
                    "type": "string",
                    "example": "English"
                },
                "originalTitle": {
                    "type": "string",
                    "example": "Avatar"
                },
                "overview": {
                    "type": "string",
                    "example": "A paraplegic Marine is dispatched to the moon"
                },
                "popularity": {
                    "type": "number",
                    "example": 321.52
                },
                "productionCompanies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Company"
                    }
                },
                "releaseDate": {
                    "type": "string",
                    "example": "2006-10-06"
                },
                "revenue": {
                    "type": "integer",
                    "example": 14821658
                },
                "runtime": {
                    "type": "number",
                    "example": 123
                },
                "status": {
                    "type": "string",
                    "example": "Released"
                },
                "tagline": {
                    "type": "string",
                    "example": "A paraplegic Marine is dispatched to the moon"
                },
                "title": {
                    "type": "string",
                    "example": "Avatar"
                },
                "voteAverage": {
                    "type": "number",
                    "example": 7.8
                },
                "voteCount": {
                    "type": "integer",
                    "example": 32132
                }
            }
        },
        "models.MoviePreview": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 123
                },
                "tagline": {
                    "type": "string",
                    "example": "A paraplegic Marine is dispatched to the moon"
                },
                "title": {
                    "type": "string",
                    "example": "Avatar"
                },
                "voteAverage": {
                    "type": "number",
                    "example": 7.8
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
