version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_movies
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
    volumes:
      - ../dockerfiles/postgres:/var/lib/postgresql/data
      - ../datasets/own-dataset:/var/datasets
      - ../scripts/sql:/var/scripts/sql
    ports:
      - '5432:5432'

  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    image: kibana:8.11.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=yourElasticPassword
      - XPACK_SECURITY_ENABLED=true
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
