version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_movies
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
    volumes:
      - ../dockerfiles/postgres:/var/lib/postgresql/data
      - ../datasets/own-dataset:/var/datasets
      - ../scripts/sql:/var/scripts/sql
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    container_name: redis_movies
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - '6379:6379'

networks:
  elastic:
    driver: bridge
