version: '3.8'

services:
  api:
    container_name: "recommendations_api"
    build:
      context: .
    ports:
      - '5566:8000'
    volumes:
      - ./static:/app/static
    environment:
      - database_host=postgres

